---
driver:
  name: vagrant
  gui: false

platforms:
  - name: windows-2016
    driver:
      box: mwrock/Windows2016
  - name: windows-2012r2
    driver:
      box: mwrock/Windows2012R2

verifier:
  name: inspec
  format: documentation

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

suites:
- name: default
  run_list:
    - "recipe[zabbix-agent]"
  attributes:
    zabbix:
      agent:
        version: 2.4.4
