# frozen_string_literal: true

name              'zabbix-agent'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides zabbix_agent resources'
source_url        'https://github.com/sous-chefs/zabbix-agent'
issues_url        'https://github.com/sous-chefs/zabbix-agent/issues'
version           '0.15.12'
chef_version      '>= 15.3'

supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2023.0'
supports 'centos_stream', '>= 9.0'
supports 'debian', '>= 12.0'
supports 'oracle', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'ubuntu', '>= 22.04'
